# build settings for the ICC2-jailbreak components.
#
# the qnx clang/lld toolchain shims, the stub libraries and the emulator stay in the ICC2
# checkout; this repo references that externally instead of carrying a copy. point ICC2_DIR
# at the ICC2 tree (default: ../../ICC2 relative to this repo, which is how the two sit in
# the maintainer's tree; override with `make ICC2_DIR=/path/to/ICC2` or the environment).
ICC2_DIR ?= $(firstword $(wildcard $(CURDIR)/../../../ICC2 $(CURDIR)/../../ICC2 \
                                     $(CURDIR)/../ICC2 $(HOME)/ICC2))
ifeq ($(wildcard $(ICC2_DIR)/sdk/config.mk),)
$(error ICC2 not found - set ICC2_DIR to the ICC2 checkout that carries sdk/ and qemu/)
endif

# ICC2's config.mk defines CC/TARGET/CFLAGS/LDFLAGS and LIBC = $(SDK)/stub/...
SDK     = $(ICC2_DIR)/sdk
include $(SDK)/config.mk

# this repo's shared unit-side runtime (moved out of the ICC2 sdk): the homebrew libraries
# and the menu ui. see common/README.md.
COMMON  = $(CURDIR)/common

# the base process/framebuffer/console/input pieces that stay in the ICC2 sdk
SDKBASE = $(SDK)/crt0.S $(SDK)/fb.c $(SDK)/console.c $(SDK)/font.c $(SDK)/input.c
# the shared homebrew runtime linked into the clients
OURCO   = $(COMMON)/hmictl.c $(COMMON)/jlog.c
# the menu ui, shared by hbmenu, buswatch, syncsploit and mediaplayer
MENUUI  = $(COMMON)/menu.c $(COMMON)/menufont.c

# the unit's usb bulk-in transport stub (libusbdi), regenerated by mkstub.py if the dump is
# around; the .so is carried in the ICC2 sdk and linked, never loaded (the unit's real one is)
USBSTUB = $(SDK)/stub/libusbdi.so.2

# include paths: the sdk headers (qnx.h, fb.h, console.h, input.h) and our shared headers
INC     = -I$(SDK) -I$(COMMON)

# ffmpeg's libav* port stays in the ICC2 sdk (it is generic, not jailbreak work); the media
# player builds against its build tree and shim
FFBUILD  = $(SDK)/ffmpeg/build
FFOBJ    = $(FFBUILD)/obj
FFPREFIX = $(FFOBJ)/prefix
FFSHIM   = $(SDK)/ffmpeg/shim
FFSDL    = $(SDK)/ffmpeg/sdl
RES      = $(shell clang -print-resource-dir)/include
# same freestanding shape as the ICC2 ffmpeg makefile: the shim is the only libc
FFCFLAGS = $(TARGET) -O2 -ffreestanding -nostdinc -isystem $(FFSHIM) -isystem $(RES) \
           -fno-pic -fno-stack-protector -ffunction-sections -fdata-sections -fomit-frame-pointer
MPCFLAGS = $(FFCFLAGS) -I$(FFOBJ) -I$(FFPREFIX)/include -I$(FFSDL) -I$(SDK) -I$(COMMON) \
           -Wno-unused-function -Wno-parentheses -Wno-macro-redefined -Wno-unused-variable -Wno-switch
FFLIBS   = $(FFPREFIX)/lib/libavformat.a $(FFPREFIX)/lib/libavcodec.a \
           $(FFPREFIX)/lib/libswscale.a $(FFPREFIX)/lib/libavutil.a
