#!/usr/bin/env python3
# bakes jailbreak/hmi_startup.sh into hookblob.h, the copy of the hook the syncsploit ui
# carries. the ui compares the file on the unit's nand against this blob (same bytes = this
# syncsploit's jailbreak, other bytes = a different one) and writes it out when the jailbreak
# button is pressed. generated at build time, so the ui can never embed a hook that differs
# from the one payload.sh installs.
#   mkhookblob.py jailbreak/hmi_startup.sh hookblob.h
import sys


def main(src, dst):
    data = open(src, 'rb').read()
    out = ['/* generated by mkhookblob.py from %s, do not edit */' % src,
           '#ifndef HOOKBLOB_H',
           '#define HOOKBLOB_H',
           '',
           'static const unsigned char synctool_hook[] = {']
    for i in range(0, len(data), 12):
        out.append('    ' + ', '.join('0x%02x' % b for b in data[i:i + 12]) + ',')
    out += ['};',
            'static const unsigned int synctool_hook_len = sizeof synctool_hook;',
            '',
            '#endif']
    open(dst, 'w').write('\n'.join(out) + '\n')
    print('hookblob.h: %d bytes from %s' % (len(data), src))


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
