#!/bin/sh
# shared post-build steps for both boards, invoked by Buildroot with
# TARGET_DIR/HOST_DIR/BINARIES_DIR in the environment.
set -eu

# systemd wants a machine-id before PID1 reads it, and the rootfs is
# read-only, so PID1 cannot generate one. livi-persist replaces it with a
# per-unit id from /data when a data partition exists; this placeholder keeps
# PID1 and early services quiet on a partitionless boot. it is not secret: the
# image ships no ssh, no logins and no network services.
if [ ! -s "$TARGET_DIR/etc/machine-id" ]; then
    printf 'b5a3f1c2d4e67890b5a3f1c2d4e67890\n' > "$TARGET_DIR/etc/machine-id"
fi

# an appliance does not need a login prompt on the release image. the debug
# defconfig sets a serial getty explicitly and this does not touch it.
rm -f "$TARGET_DIR/etc/systemd/system/multi-user.target.wants/serial-getty@"*.service

# the pulseaudio package ships and presets pulseaudio.service, a second
# unconfigured daemon that starts before livi-pulse and takes /run/pulse/pid,
# so livi-pulse cannot create its own; that failure used to hold livi.service
# (After=livi-pulse) for ~30 s behind the old retrying ExecStartPost. mask it;
# livi-pulse is the only daemon. the mask also beats systemd's later
# preset-all because a /dev/null symlink makes the unit unloadable (a .wants
# symlink is then harmless).
#
# cups is only needed for GTK printing, which this appliance never does, and
# its socket/path units add work to every boot; mask them too.
mask_unit() {
    ln -sf /dev/null "$TARGET_DIR/etc/systemd/system/$1"
}
mkdir -p "$TARGET_DIR/etc/systemd/system"
mask_unit pulseaudio.service
mask_unit cups.service
mask_unit cups.path
mask_unit cups.socket

# nothing reads systemd credentials and there is no networkd to consume the
# generated network units; both services only do work at boot
mask_unit systemd-network-generator.service
mask_unit systemd-udev-load-credentials.service

# systemd-udev-trigger's stock ExecStart coldplugs every device in the system
# (module,block,net,tty,input,...) and costs 2-3 s on the appliance's slow
# CPU. nothing here needs that coldplug: the kernel has every boot-path driver
# built in and devtmpfs carries the nodes, livi-persist mounts the data
# partition by its fixed /dev node (never the by-label symlink udev would
# create), and systemd-udevd itself still runs for live events (the car
# plugging in, a card inserted later). mask the unit in every image.
rm -f "$TARGET_DIR/etc/systemd/system/systemd-udev-trigger.service"
rm -rf "$TARGET_DIR/etc/systemd/system/systemd-udev-trigger.service.d"
ln -sf /dev/null "$TARGET_DIR/etc/systemd/system/systemd-udev-trigger.service"

# the qemu and debug images want a serial getty, and the stock
# serial-getty@.service pulls in its own device unit (BindsTo=dev-%i.device)
# rather than waiting for one that already exists. with the coldplug masked
# that unit never appears and the getty holds multi-user.target for the 90 s
# device timeout. the tty node is in devtmpfs the whole time, so start agetty
# from a unit with no device dependency at all. the release board image
# (GETTY_PORT empty) installs nothing and boots no getty.
GETTY_CONF="$TARGET_DIR/usr/lib/systemd/system/serial-getty@.service.d/buildroot-console.conf"
GETTY_PORT=""
if [ -f "$GETTY_CONF" ]; then
    GETTY_PORT=$(sed -n 's/^DefaultInstance=//p' "$GETTY_CONF" | head -n 1)
fi
rm -f "$TARGET_DIR/etc/systemd/system/livi-console-getty.service"
if [ -n "$GETTY_PORT" ]; then
    cat > "$TARGET_DIR/etc/systemd/system/livi-console-getty.service" <<EOF
# generated by board/common/post-build.sh: a serial getty that does not wait
# on a systemd device unit (which needs the udev coldplug, masked above).
[Unit]
Description=Serial console getty on $GETTY_PORT (no udev device unit)
DefaultDependencies=no
After=systemd-journald.socket
Before=getty.target shutdown.target
Conflicts=shutdown.target

[Service]
Type=idle
ExecStart=-/sbin/agetty --noreset --noclear --keep-baud 115200,57600,38400,9600 - $GETTY_PORT linux
Restart=always
UtmpIdentifier=$GETTY_PORT
StandardInput=tty
StandardOutput=tty
TTYPath=/dev/$GETTY_PORT
TTYReset=yes
TTYVHangup=yes
KillMode=process
SendSIGHUP=yes

[Install]
WantedBy=getty.target
EOF
    mkdir -p "$TARGET_DIR/etc/systemd/system/getty.target.wants"
    ln -sf ../livi-console-getty.service \
        "$TARGET_DIR/etc/systemd/system/getty.target.wants/livi-console-getty.service"
fi

# belt and braces: the kernel parameter systemd.getty_auto=0 disables the
# generator that would create the stock serial getty from console= (ttyAMA0
# on qemu, ttyS0 on the debug board, ttynull on the release board), but a
# missed parameter would put that getty back on the 90 s device-unit timeout.
# mask the stock instances for the known consoles; livi-console-getty (if
# any) already covers GETTY_PORT.
for p in ttyAMA0 ttyS0 ttynull; do
    ln -sf /dev/null "$TARGET_DIR/etc/systemd/system/serial-getty@$p.service"
done

# busybox installs a tiny /etc/init.d skeleton even under systemd; keep it
# out of the way so nothing thinks sysv init is in charge
rm -rf "$TARGET_DIR/etc/init.d"

# the persistent-state directory and the home the services use
mkdir -p "$TARGET_DIR/home/user" "$TARGET_DIR/data"
chmod 0755 "$TARGET_DIR/home/user"
