/* text in the unit's own HMI font (Arial), drawn proportionally on the framebuffer. the glyph
 * table is generated by mkmenufont.py; this is the rasteriser the homebrew menu draws with. */
#ifndef MENU_H
#define MENU_H

#include "fb.h"

/* one glyph: offset into the bit table, then a bitmap w pixels wide and h rows tall. rows
 * are byte padded, leftmost pixel in the top bit. the glyph cell puts the baseline at
 * MENU_FONT_ASCENT (menufont.h), so a draw with the baseline at y is y - MENU_FONT_ASCENT. */
struct menu_glyph {
    unsigned short off;
    unsigned char w, h;
};

extern const struct menu_glyph menu_font_glyphs[];
extern const unsigned char menu_font_bits[];

/* text with its baseline at y, proportional widths, ascii only (anything else draws '?') */
void menu_text(struct fb *fb, int x, int y, pixel colour, const char *text);
int menu_text_width(const char *text);

/* the same rasteriser over an explicit face and bit table, for the second size menufont.c
 * carries (the player exit button label). scale multiplies every glyph pixel, the way the
 * console font's rasteriser used to, so a face can be drawn at more than one size */
void menu_text_face(struct fb *fb, const struct menu_glyph *glyphs, const unsigned char *bits,
                    int ascent, int scale, int x, int baseline, pixel colour, const char *text);
int menu_text_face_width(const struct menu_glyph *glyphs, int scale, const char *text);

#endif
