#!/usr/bin/env python3
# renders the proportional bitmap font the homebrew ui draws with (menu.c) into
# menufont.c/.h. the hmi uses it around 30px for menu rows and titles, and the players'
# status cards use three sizes: a 44px wordmark, 30px headings and 16px body/exit text.
#
# the unit's own font is Arial: when the ICC2 dump is there this renders ari_____.ttf, so
# the ui matches the hmi. a public build has no dump art, so the fallback is a metrically
# compatible free font (Liberation Sans), which keeps the same layout. the generated files
# are not checked in - make and build.sh run this first. HMI_FONT or the first argument
# picks an explicit ttf.
#
#     python3 mkmenufont.py [font.ttf]
import os
import sys
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
ICC2 = os.environ.get('ICC2_DIR') or os.path.normpath(os.path.join(ROOT, '..', '..', '..', 'ICC2'))
DUMP_FONT = os.path.join(ICC2, 'dump', 'packages/factory/hmi/root_dir/usr/hmi/Fonts/ari_____.ttf')
# Arial-metric and redistributable first, then any common free sans
FALLBACKS = (
    '/usr/share/fonts/liberation-sans-fonts/LiberationSans-Regular.ttf',
    '/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf',
    '/usr/share/fonts/TTF/DejaVuSans.ttf',
    '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
)


def default_font():
    if os.path.exists(DUMP_FONT):
        return DUMP_FONT
    for path in FALLBACKS:
        if os.path.exists(path):
            return path
    sys.exit('mkmenufont: no font found - install liberation-sans or dejavu, extract the '
             'ICC2 dump, or set HMI_FONT=/path/to/font.ttf')
SIZE = 30
SMALL = 16
BIG = 44
FIRST, LAST = 32, 126
THRESHOLD = 100


def render(ttf, size):
    font = ImageFont.truetype(ttf, size)
    ascent, descent = font.getmetrics()
    cell_h = ascent + descent
    out = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        w = max(1, round(font.getlength(ch)))
        im = Image.new('L', (w, cell_h), 0)
        ImageDraw.Draw(im).text((0, 0), ch, font=font, fill=255)
        px = im.load()
        stride = (w + 7) // 8
        bits = bytearray(stride * cell_h)
        for y in range(cell_h):
            for x in range(w):
                if px[x, y] >= THRESHOLD:
                    bits[y * stride + x // 8] |= 0x80 >> (x % 8)
        out.append((w, cell_h, bytes(bits)))
    return ascent, descent, out


def table(glyph_rows):
    data = bytearray()
    rows = []
    for w, h, bits in glyph_rows:
        off = len(data)
        data += bits
        rows.append((off, w, h))
    return rows, data


def write_glyphs(f, name, rows):
    f.write('const struct menu_glyph %s[%d] = {\n' % (name, len(rows)))
    for off, w, h in rows:
        f.write('    { %d, %d, %d },\n' % (off, w, h))
    f.write('};\n\n')


def write_bits(f, name, data):
    f.write('const unsigned char %s[%d] = {\n' % (name, len(data)))
    for i in range(0, len(data), 16):
        f.write('    ' + ','.join('0x%02x' % b for b in data[i:i + 16]) + ',\n')
    f.write('};\n')


def main(ttf):
    ascent, descent, mid = render(ttf, SIZE)
    small_ascent, small_descent, small = render(ttf, SMALL)
    big_ascent, big_descent, big = render(ttf, BIG)
    rows, data = table(mid)
    small_rows, small_data = table(small)
    big_rows, big_data = table(big)
    with open(os.path.join(HERE, 'menufont.h'), 'w') as f:
        f.write('/* generated by mkmenufont.py, do not edit. see menu.h for the glyph layout */\n')
        f.write('#ifndef MENUFONT_H\n#define MENUFONT_H\n\n')
        f.write('#include "menu.h"\n\n')
        f.write(f'#define MENU_FONT_ASCENT  {ascent}\n')
        f.write(f'#define MENU_FONT_DESCENT {descent}\n')
        f.write(f'#define MENU_FONT_SMALL_ASCENT  {small_ascent}\n')
        f.write(f'#define MENU_FONT_SMALL_DESCENT {small_descent}\n')
        f.write(f'#define MENU_FONT_BIG_ASCENT  {big_ascent}\n')
        f.write(f'#define MENU_FONT_BIG_DESCENT {big_descent}\n\n')
        f.write('extern const struct menu_glyph menu_font_glyphs[%d];\n' % len(rows))
        f.write('extern const unsigned char menu_font_bits[%d];\n' % len(data))
        f.write('extern const struct menu_glyph menu_font_small_glyphs[%d];\n' % len(small_rows))
        f.write('extern const unsigned char menu_font_small_bits[%d];\n' % len(small_data))
        f.write('extern const struct menu_glyph menu_font_big_glyphs[%d];\n' % len(big_rows))
        f.write('extern const unsigned char menu_font_big_bits[%d];\n\n#endif\n' % len(big_data))
    with open(os.path.join(HERE, 'menufont.c'), 'w') as f:
        f.write('/* generated by mkmenufont.py, do not edit */\n#include "menufont.h"\n\n')
        write_glyphs(f, 'menu_font_glyphs', rows)
        write_bits(f, 'menu_font_bits', data)
        f.write('\n')
        write_glyphs(f, 'menu_font_small_glyphs', small_rows)
        write_bits(f, 'menu_font_small_bits', small_data)
        f.write('\n')
        write_glyphs(f, 'menu_font_big_glyphs', big_rows)
        write_bits(f, 'menu_font_big_bits', big_data)
    print(f'mkmenufont: {len(rows)} glyphs, {len(data)} + {len(small_data)} + {len(big_data)} bytes, from {ttf}')


if __name__ == '__main__':
    ttf = (sys.argv[1] if len(sys.argv) > 1
           else os.environ.get('HMI_FONT') or default_font())
    main(ttf)
