/*
 * generated by mksignals.py from ../qemu/v850_messages.py, do not edit.
 * the v850 codec tables (channel, message id, version, length, {signal: (byte, start bit, bits)}).
 * a wide signal stores its low byte at `byte` and grows into lower indexed bytes, so
 * value = (d[byte-n+1 .. byte] big endian little endian concat) >> bit. see v850.py pack().
 */
#ifndef BUSSIGNALS_H
#define BUSSIGNALS_H

struct bussig {
    const char *name;
    unsigned char byte, bit, bits;
};

struct busmsg {
    const char *name;
    unsigned char ch, id, version, len, nsigs;
    const struct bussig *sigs;
};

static const struct bussig sig_acm_status[] = {
    { "dp_0d0", 0, 6, 1 },
};

static const struct bussig sig_acm_tone[] = {
    { "dp_2f1", 0, 2, 6 },
    { "audio_reset", 0, 1, 1 },
    { "dp_47b", 0, 0, 1 },
    { "balance_fade_preset", 1, 5, 3 },
    { "bass", 1, 0, 5 },
    { "mid", 2, 0, 5 },
    { "treble", 3, 0, 5 },
    { "balance", 5, 3, 5 },
    { "fade", 6, 6, 5 },
};

static const struct bussig sig_acm_cd[] = {
    { "track", 0, 0, 8 },
    { "state", 2, 1, 4 },
    { "dp_030", 2, 0, 1 },
    { "play_mode", 2, 5, 3 },
};

static const struct bussig sig_acm_eq[] = {
    { "band1", 0, 0, 5 },
    { "band2", 1, 0, 5 },
    { "band3", 2, 0, 5 },
    { "band4", 3, 0, 5 },
    { "band5", 4, 0, 5 },
    { "preset", 4, 5, 3 },
};

static const struct bussig sig_acm_volume[] = {
    { "volume", 0, 0, 6 },
    { "media_volume", 2, 0, 6 },
    { "dp_00d", 3, 0, 6 },
    { "dp_00a", 4, 0, 4 },
    { "dp_1b4", 5, 4, 1 },
    { "security_ok", 5, 0, 1 },
};

static const struct bussig sig_acm_tuner[] = {
    { "mode", 0, 0, 8 },
    { "khz", 3, 0, 18 },
};

static const struct bussig sig_acm_play[] = {
    { "dp_03a", 5, 0, 18 },
    { "seconds", 2, 0, 24 },
};

static const struct bussig sig_him_state[] = {
    { "ac_off", 0, 7, 1 },
    { "recirc", 0, 6, 1 },
    { "fresh_air", 0, 5, 1 },
    { "air_face", 0, 4, 1 },
    { "air_feet", 0, 3, 1 },
    { "front_demist", 0, 2, 1 },
    { "climate_man", 0, 1, 1 },
    { "fan_icon", 0, 0, 1 },
    { "outside_temp_shown", 1, 7, 1 },
    { "passenger_temp_shown", 1, 4, 1 },
    { "driver_temp_shown", 1, 3, 1 },
    { "auto", 1, 2, 1 },
    { "semi_auto", 1, 1, 1 },
    { "climate_off", 1, 0, 1 },
    { "passenger_temp", 2, 0, 8 },
    { "driver_temp", 3, 0, 8 },
    { "outside_temp", 4, 0, 8 },
    { "rear_demist", 7, 5, 1 },
    { "ac_on", 7, 4, 1 },
    { "fan_speed", 7, 0, 4 },
};

static const struct bussig sig_vehicle_state[] = {
    { "crank", 0, 0, 8 },
    { "gear", 1, 0, 8 },
    { "ignition", 2, 0, 8 },
    { "rtc_temperature", 3, 0, 8 },
    { "illumination", 4, 0, 8 },
};

static const struct bussig sig_vehicle_menus[] = {
    { "locking1", 0, 5, 3 },
    { "locking2", 0, 2, 3 },
    { "locking3", 1, 7, 3 },
    { "locking4", 1, 6, 1 },
    { "unlocking1", 1, 3, 3 },
    { "unlocking2", 1, 0, 3 },
    { "unlocking3", 2, 4, 1 },
    { "lighting1", 2, 1, 3 },
    { "dp_103", 4, 5, 3 },
    { "lighting2", 4, 2, 3 },
    { "lighting3", 5, 7, 3 },
    { "lighting4", 5, 4, 3 },
    { "lighting5", 5, 1, 3 },
    { "lighting6", 5, 0, 1 },
    { "alarm1", 6, 5, 3 },
    { "alarm2", 6, 2, 3 },
    { "alarm3", 7, 7, 3 },
    { "alarm4", 7, 4, 3 },
    { "alarm5", 7, 3, 1 },
    { "locking5", 7, 0, 3 },
};

static const struct bussig sig_vehicle_dp394[] = {
    { "dp_394", 1, 0, 16 },
    { "dp_368", 3, 0, 16 },
};

static const struct bussig sig_vehicle_pam[] = {
    { "dp_2d0", 0, 7, 1 },
    { "dp_302", 0, 6, 1 },
    { "dp_36a", 0, 5, 1 },
    { "region1", 0, 0, 4 },
    { "region2", 1, 4, 4 },
    { "region3", 1, 0, 4 },
    { "region4", 2, 0, 4 },
};

static const struct bussig sig_vehicle_config[] = {
    { "dp_39d", 0, 7, 1 },
    { "night", 0, 6, 1 },
    { "camera_fitted", 0, 5, 1 },
    { "theme", 0, 3, 2 },
    { "vehicle_type", 0, 0, 3 },
    { "dp_639", 1, 0, 8 },
    { "dp_39b", 2, 0, 8 },
    { "dp_399", 3, 0, 8 },
    { "dp_398", 4, 0, 8 },
    { "dp_39a", 5, 0, 8 },
    { "dp_397", 7, 0, 16 },
    { "dp_39c", 9, 0, 16 },
    { "climate_mode", 10, 6, 2 },
    { "serial", 14, 0, 32 },
    { "navi_serial", 18, 0, 32 },
};

static const struct bussig sig_vehicle_dp3c9[] = {
    { "dp_3cb", 0, 0, 8 },
    { "dp_3cc", 1, 6, 2 },
    { "dp_3c9", 2, 0, 12 },
    { "dp_3ca", 4, 0, 16 },
};

#define BUS_SIGNAL_COUNT 103

static const struct busmsg bus_messages[] = {
    { "acm.status", 0x02, 0x00, 3, 1, 1, sig_acm_status },
    { "acm.tone", 0x02, 0x02, 3, 7, 9, sig_acm_tone },
    { "acm.cd", 0x02, 0x0a, 3, 3, 4, sig_acm_cd },
    { "acm.eq", 0x02, 0x0b, 3, 5, 6, sig_acm_eq },
    { "acm.volume", 0x02, 0x0c, 3, 6, 6, sig_acm_volume },
    { "acm.tuner", 0x02, 0x11, 4, 4, 2, sig_acm_tuner },
    { "acm.play", 0x02, 0x13, 1, 6, 2, sig_acm_play },
    { "him.state", 0x03, 0x00, 1, 8, 20, sig_him_state },
    { "vehicle.state", 0x04, 0x00, 7, 5, 5, sig_vehicle_state },
    { "vehicle.menus", 0x04, 0x01, 2, 8, 20, sig_vehicle_menus },
    { "vehicle.dp394", 0x04, 0x04, 2, 4, 2, sig_vehicle_dp394 },
    { "vehicle.pam", 0x04, 0x05, 2, 3, 7, sig_vehicle_pam },
    { "vehicle.config", 0x04, 0x06, 5, 19, 15, sig_vehicle_config },
    { "vehicle.dp3c9", 0x04, 0x07, 1, 5, 4, sig_vehicle_dp3c9 },
};

#define BUS_MESSAGE_COUNT ((int)(sizeof bus_messages / sizeof bus_messages[0]))

struct busbutton {
    const char *name;
    unsigned char bit;
};

static const struct busbutton bus_buttons[] = {
    { "power", 0 },
    { "lock", 1 },
    { "cabin lights", 2 },
    { "hazard", 3 },
    { "eject", 4 },
    { "unlock", 5 },
    { "climate off", 6 },
    { "recirculate", 7 },
    { "a/c", 8 },
    { "auto", 9 },
    { "pass temp down", 11 },
    { "pass temp up", 12 },
    { "fan down", 13 },
    { "fan up", 14 },
    { "air distribution", 16 },
    { "front demist", 17 },
    { "driver temp down", 18 },
    { "driver temp up", 19 },
    { "rear demist", 20 },
    { "dsc", 21 },
    { "scn/as", 22 },
    { "cd/aux", 23 },
    { "fm/am", 24 },
    { "unnamed 25", 25 },
    { "load", 26 },
    { "ok", 27 },
    { "menu", 28 },
    { "seek down", 29 },
    { "seek up", 30 },
    { "unnamed 36", 36 },
    { "unnamed 37", 37 },
    { "unnamed 38", 38 },
    { "unnamed 41", 41 },
    { "unnamed 42", 42 },
    { "unnamed 43", 43 },
    { "swc phone", 46 },
    { "swc mode", 47 },
    { "swc seek", 48 },
    { "swc volume up", 49 },
    { "swc volume down", 50 },
    { "unnamed 52", 52 },
};

#define BUS_BUTTON_COUNT ((int)(sizeof bus_buttons / sizeof bus_buttons[0]))

struct bushint {
    const char *msg, *sig, *text;
    int value;
};

static const struct bushint bus_hints[] = {
    { "vehicle.state", "ignition", "off", 1 },
    { "vehicle.state", "ignition", "acc", 2 },
    { "vehicle.state", "ignition", "run", 3 },
    { "vehicle.state", "ignition", "start", 4 },
    { "vehicle.state", "crank", "not cranking", 0 },
    { "vehicle.state", "gear", "forward", 0 },
    { "vehicle.state", "gear", "reverse", 11 },
    { "vehicle.config", "theme", "classic", 0 },
    { "vehicle.config", "theme", "kinetic", 1 },
    { "vehicle.config", "theme", "borderless", 2 },
    { "vehicle.config", "climate_mode", "none", 0 },
    { "vehicle.config", "climate_mode", "single", 1 },
    { "vehicle.config", "climate_mode", "dual", 2 },
    { "acm.tuner", "mode", "audio off", 0 },
    { "acm.tuner", "mode", "mp3 cd", 2 },
    { "acm.tuner", "mode", "AM", 3 },
    { "acm.tuner", "mode", "AMAS", 4 },
    { "acm.tuner", "mode", "FM1", 5 },
    { "acm.tuner", "mode", "FM2", 6 },
    { "acm.tuner", "mode", "FMAS", 7 },
    { "acm.tuner", "mode", "code error", 13 },
    { "acm.cd", "state", "play", 0 },
    { "acm.cd", "state", "pause", 1 },
    { "acm.cd", "state", "fast fwd", 2 },
    { "acm.cd", "state", "rewind", 3 },
    { "acm.cd", "state", "no disc", 4 },
    { "acm.cd", "state", "eject", 5 },
    { "acm.cd", "state", "reading", 6 },
    { "acm.cd", "state", "off", 7 },
    { "acm.cd", "state", "loading", 8 },
};

#define BUS_HINT_COUNT ((int)(sizeof bus_hints / sizeof bus_hints[0]))

#endif
