#!/usr/bin/env python3
# bakes the v850 signal tables (../qemu/v850_messages.py, the same ones the car emulator speaks)
# into bussignals.h for the on-unit bus watch app. run from the repo root or via make.
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
ICC2 = os.environ.get('ICC2_DIR') or os.path.normpath(os.path.join(REPO, '..', '..', '..', 'ICC2'))
sys.path.insert(0, os.path.join(ICC2, 'qemu'))
import v850_messages

OUT = os.path.join(HERE, 'bussignals.h')


def cstr(text):
    return '"' + text.replace('\\', '\\\\').replace('"', '\\"') + '"'


def cname(msg):
    return ''.join(ch if ch.isalnum() else '_' for ch in msg)


def hints():
    rows = [
        ('vehicle.state', 'ignition', 1, 'off'),
        ('vehicle.state', 'ignition', 2, 'acc'),
        ('vehicle.state', 'ignition', 3, 'run'),
        ('vehicle.state', 'ignition', 4, 'start'),
        ('vehicle.state', 'crank', 0, 'not cranking'),
        ('vehicle.state', 'gear', 0, 'forward'),
        ('vehicle.state', 'gear', 0x0b, 'reverse'),
        ('vehicle.config', 'theme', 0, 'classic'),
        ('vehicle.config', 'theme', 1, 'kinetic'),
        ('vehicle.config', 'theme', 2, 'borderless'),
        ('vehicle.config', 'climate_mode', 0, 'none'),
        ('vehicle.config', 'climate_mode', 1, 'single'),
        ('vehicle.config', 'climate_mode', 2, 'dual'),
        # acm media mode, the values the hmi's dp 0x8a takes (v850-ipc-protocol.md)
        ('acm.tuner', 'mode', 0, 'audio off'),
        ('acm.tuner', 'mode', 2, 'mp3 cd'),
        ('acm.tuner', 'mode', 3, 'AM'),
        ('acm.tuner', 'mode', 4, 'AMAS'),
        ('acm.tuner', 'mode', 5, 'FM1'),
        ('acm.tuner', 'mode', 6, 'FM2'),
        ('acm.tuner', 'mode', 7, 'FMAS'),
        ('acm.tuner', 'mode', 0x0d, 'code error'),
        # cd transport states, doc 0x0a d2 bits4..1
        ('acm.cd', 'state', 0, 'play'),
        ('acm.cd', 'state', 1, 'pause'),
        ('acm.cd', 'state', 2, 'fast fwd'),
        ('acm.cd', 'state', 3, 'rewind'),
        ('acm.cd', 'state', 4, 'no disc'),
        ('acm.cd', 'state', 5, 'eject'),
        ('acm.cd', 'state', 6, 'reading'),
        ('acm.cd', 'state', 7, 'off'),
        ('acm.cd', 'state', 8, 'loading'),
    ]
    return rows


# the front panel bitmap (docs/v850-ipc-protocol.md), bit -> fascia name
BUTTONS = [
    (0, 'power'), (1, 'lock'), (2, 'cabin lights'), (3, 'hazard'), (4, 'eject'), (5, 'unlock'),
    (6, 'climate off'), (7, 'recirculate'), (8, 'a/c'), (9, 'auto'), (11, 'pass temp down'),
    (12, 'pass temp up'), (13, 'fan down'), (14, 'fan up'), (16, 'air distribution'),
    (17, 'front demist'), (18, 'driver temp down'), (19, 'driver temp up'), (20, 'rear demist'),
    (21, 'dsc'), (22, 'scn/as'), (23, 'cd/aux'), (24, 'fm/am'), (25, 'unnamed 25'), (26, 'load'),
    (27, 'ok'), (28, 'menu'), (29, 'seek down'), (30, 'seek up'),
    (36, 'unnamed 36'), (37, 'unnamed 37'), (38, 'unnamed 38'),
    (41, 'unnamed 41'), (42, 'unnamed 42'), (43, 'unnamed 43'),
    (46, 'swc phone'), (47, 'swc mode'), (48, 'swc seek'), (49, 'swc volume up'),
    (50, 'swc volume down'), (52, 'unnamed 52'),
]


def main():
    messages = sorted(v850_messages.MESSAGES.items(), key=lambda kv: (kv[1][0], kv[1][1]))
    lines = []
    lines.append('/*')
    lines.append(' * generated by mksignals.py from ../qemu/v850_messages.py, do not edit.')
    lines.append(' * the v850 codec tables (channel, message id, version, length, {signal: (byte, start bit, bits)}).')
    lines.append(' * a wide signal stores its low byte at `byte` and grows into lower indexed bytes, so')
    lines.append(' * value = (d[byte-n+1 .. byte] big endian little endian concat) >> bit. see v850.py pack().')
    lines.append(' */')
    lines.append('#ifndef BUSSIGNALS_H')
    lines.append('#define BUSSIGNALS_H')
    lines.append('')
    lines.append('struct bussig {')
    lines.append('    const char *name;')
    lines.append('    unsigned char byte, bit, bits;')
    lines.append('};')
    lines.append('')
    lines.append('struct busmsg {')
    lines.append('    const char *name;')
    lines.append('    unsigned char ch, id, version, len, nsigs;')
    lines.append('    const struct bussig *sigs;')
    lines.append('};')
    lines.append('')
    count = 0
    for msg, (ch, mid, version, length, signals) in messages:
        lines.append('static const struct bussig sig_%s[] = {' % cname(msg))
        for name, (byte, bit, bits) in signals.items():
            lines.append('    { %s, %u, %u, %u },' % (cstr(name), byte, bit, bits))
            count += 1
        lines.append('};')
        lines.append('')
    lines.append('#define BUS_SIGNAL_COUNT %d' % count)
    lines.append('')
    lines.append('static const struct busmsg bus_messages[] = {')
    for msg, (ch, mid, version, length, signals) in messages:
        lines.append('    { %s, 0x%02x, 0x%02x, %u, %u, %u, sig_%s },' %
                     (cstr(msg), ch, mid, version, length, len(signals), cname(msg)))
    lines.append('};')
    lines.append('')
    lines.append('#define BUS_MESSAGE_COUNT ((int)(sizeof bus_messages / sizeof bus_messages[0]))')
    lines.append('')
    lines.append('struct busbutton {')
    lines.append('    const char *name;')
    lines.append('    unsigned char bit;')
    lines.append('};')
    lines.append('')
    lines.append('static const struct busbutton bus_buttons[] = {')
    for bit, name in BUTTONS:
        lines.append('    { %s, %u },' % (cstr(name), bit))
    lines.append('};')
    lines.append('')
    lines.append('#define BUS_BUTTON_COUNT ((int)(sizeof bus_buttons / sizeof bus_buttons[0]))')
    lines.append('')
    lines.append('struct bushint {')
    lines.append('    const char *msg, *sig, *text;')
    lines.append('    int value;')
    lines.append('};')
    lines.append('')
    lines.append('static const struct bushint bus_hints[] = {')
    for msg, sig, value, text in hints():
        lines.append('    { %s, %s, %s, %d },' % (cstr(msg), cstr(sig), cstr(text), value))
    lines.append('};')
    lines.append('')
    lines.append('#define BUS_HINT_COUNT ((int)(sizeof bus_hints / sizeof bus_hints[0]))')
    lines.append('')
    lines.append('#endif')
    lines.append('')

    with open(OUT, 'w') as f:
        f.write('\n'.join(lines))
    print('wrote', OUT, '(%d signals in %d messages)' % (count, len(messages)))


if __name__ == '__main__':
    main()
